market-api.key=crpmRj7p3idzuOcrXmPL1h52q2n2U3vL
market-api.url=https://api.polygon.io/
market-api.endpoint.all-tickers=v3/reference/tickers?active=true&order=asc&limit=1000&sort=ticker&apiKey=

# 0 - ticker, 1 - date YYYY-MM-DD
market-api.endpoint.tickerOverview=v3/reference/tickers/{0}?date={1}&apiKey=
# 0 - ticker, 1 - date YYYY-MM-DD
market-api.endpoint.daily-ticker-summary=v1/open-close/{0}/{1}?adjusted=true&apiKey=
# 0 - date YYYY-MM-DD
market-api.endpoint.daily-market-summary=v2/aggs/grouped/locale/us/market/stocks/{0}?adjusted=true&apiKey=
# top gainers
market-api.endpoint.top-gainers=v2/snapshot/locale/us/markets/stocks/gainers?apiKey=
# top losers
market-api.endpoint.top-losers=v2/snapshot/locale/us/markets/stocks/losers?apiKey=
# market holidays
market-api.endpoint.market-holiday=v1/marketstatus/upcoming?apiKey=

database.url=jdbc:mariadb://192.168.0.27:3306/PILLOWDB
database.username=pillow_user
database.password=.5133p1ng.

rabbitmq.username=admin
rabbitmq.password=.h0tr0d.
rabbitmq.ip=192.168.0.27
rabbitmq.threads=1

