# Default logging level
.level=INFO

# Console handler (prints logs to the console)
handlers=java.util.logging.ConsoleHandler, java.util.logging.FileHandler

# Console handler settings
java.util.logging.ConsoleHandler.level=INFO
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter

# File handler settings (log to file)
java.util.logging.FileHandler.level=FINE
java.util.logging.FileHandler.pattern=logs/optimus.log
java.util.logging.FileHandler.limit=50000
java.util.logging.FileHandler.count=1
java.util.logging.FileHandler.formatter=java.util.logging.SimpleFormatter